//Actions

export const authActions = {
    GET_AUTH_DATA_SUCCESS : "GET_AUTH_DATA_SUCCESS",
    GET_AUTH_DATA_FAILURE : "GET_AUTH_DATA_FAILURE",
    RESET_AUTH_DATA_ERROR : "RESET_AUTH_DATA_ERROR"
}

export const addNewUserActions = {
    ADD_NEW_USER_SUCCESS : "ADD_NEW_USER_SUCCESS",
    ADD_NEW_USER_FAILURE : "ADD_NEW_USER_FAILURE",
    RESET_ADD_NEW_USER_ERROR: "RESET_ADD_NEW_USER_ERROR"
}

export const fetchTokenDetailsActions = {
   FETCH_TOKEN_DETAILS_SUCCESS : "FETCH_TOKEN_DETAILS_SUCCESS",
   RESET_TOKEN_DETAILS_STATE: "RESET_TOKEN_DETAILS_STATE"
}

export const logoutActions = {
    LOGOUT_SUCCESS : "LOGOUT_SUCCESS",
    RESER_LOGOUT_STATE : "RESER_LOGOUT_STATE"
}

export const getUsersActions = {
    GET_USERS_SUCCESS : "GET_USERS_SUCCESS",
    GET_USERS_FAILURE : "GET_USERS_FAILURE",
    RESET_GET_USERS_STATE : "RESET_GET_USERS_STATE"
}

export const selectedUserActions = {
    SELECTED_USER : "SELECTED_USER",
    RESET_USER: "RESET_USER"
}
export const notficationsActions = {
    NOTFICATIONS : "NOTFICATIONS"
}

// Actions for chats 

export const createChatActions = {
    CREATE_CHAT_SUCCESS : "CREATE_CHAT_SUCCESS",
    CREATE_CHAT_FAILUER : "CREATE_CHAT_FAILUER"
}

export const getChatsActions = {
    GET_CHATS_SUCCESS : "GET_CHATS_SUCCESS",
    GET_CHATS_FAILUER : "GET_CHATS_FAILUER"
}

export const getMessagesActions = {
    GET_MESSAGES_SUCCESS : "GET_MESSAGES_SUCCESS",
    GET_MESSAGES_FAILUER : "GET_MESSAGES_FAILUER",
    RESET_MESSAGES: "RESET_MESSAGES"
}

//Actions for groups

export const createGroupActions = {
    CREATE_GROUP_SUCCESS : "CREATE_GROUP_SUCCESS",
    CREATE_GROUP_FAILUER : "CREATE_GROUP_FAILUER",
    RESET_GROUP_STATE : "RESET_GROUP_STATE"
}

export const leaveGroupActions = {
    LEAVE_GROUP_SUCCESS : "LEAVE_GROUP_SUCCESS",
    LEAVE_GROUP_FAILURE : "LEAVE_GROUP_FAILURE",
    RESET_LEAVE_GROUP_STATE:"RESET_LEAVE_GROUP_STATE"
}

export const updateGroupNameActions = {
    UPADTE_GROUP_NAME_SUCCESS : "UPADTE_GROUP_NAME_SUCCESS",
    UPADTE_GROUP_NAME_FAILURE : "UPADTE_GROUP_NAME_FAILURE",
}

export const addNewMembersActions = {
    ADD_NEW_MEMBERS_SUCCESS : "ADD_NEW_MEMBERS_SUCCESS",
    ADD_NEW_MEMBERS_FAILURE : "ADD_NEW_MEMBERS_FAILURE"
}

export const removeMembersActions = {
    REMOVE_MEMBERS_SUCCESS : "REMOVE_MEMBERS_SUCCESS",
    REMOVE_MEMBERS_FAILURE : "REMOVE_MEMBERS_FAILURE"
}

export const sendNewMessageActions = {
    SEND_NEW_MESSAGE_SUCCESS: "SEND_NEW_MESSAGE_SUCCESS",
    SEND_NEW_MESSAGE_FAILURE : "SEND_NEW_MESSAGE_FAILURE"
}




